version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./Backend_Spring_Boot
      dockerfile: Dockerfile
    container_name: textmate_backend
    ports:
      - '8000:8000'
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/textmate
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: textmate_frontend
    ports:
      - '5000:80'
    depends_on:
      - backend
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongodb_data: {}