version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: textmate_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./Backend_Spring_Boot
      dockerfile: Dockerfile
    container_name: textmate_backend
    ports:
      - '8000:8000'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/textmate_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: textmate_frontend
    ports:
      - '5000:80'
    depends_on:
      - backend
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data: {}
